# Generated by Django 5.1.4 on 2025-01-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
